CREATE DATABASE BAITHI

USE BAITHI

CREATE TABLE KHACHHANG 
(
	MAKH VARCHAR(4) PRIMARY KEY,
	TENKH VARCHAR(40),
	DIACHI VARCHAR(40),
	LOAIKH VARCHAR(20)
)

CREATE TABLE LOAICAY 
(
	MALC VARCHAR(4) PRIMARY KEY,
	TENLC VARCHAR(40),
	XUATXU VARCHAR(20),
	GIA MONEY
)

CREATE TABLE HOADON 
(
	SOHD VARCHAR(5) PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH VARCHAR(4)
	FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	KHUYENMAI INT
)

CREATE TABLE CTHD 
(
	SOHD VARCHAR(5),
	MALC VARCHAR(4),
	PRIMARY KEY (SOHD,MALC),
	SOLUONG INT,
	FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	FOREIGN KEY (MALC) REFERENCES LOAICAY(MALC)
)
SET DATEFORMAT DMY

-----CAU 2----
INSERT INTO KHACHHANG (MAKH,TENKH,DIACHI,LOAIKH) VALUES
('KH01','Liz Kim Cuong','Ha Noi','Vang lai'),
('KH02','Inove Dieu Linh','Da Nang','Thuong xuyen'),
('KH03','Emma Nhat Khanh','TP.HCM','Vang lai')

INSERT INTO LOAICAY (MALC,TENLC,XUATXU,GIA) VALUES  
('LC01','Xuong rong tai tho','Mexico','180000'),
('LC02','Sen thach ngoc','Anh','300000'),
('LC03','Ba mau rau','Nam Phi','270000')

INSERT INTO HOADON (SOHD,NGHD,MAKH,KHUYENMAI) VALUES
('00001','22/11/2017','KH01','5'),
('00002','04/12/2017','KH03','5'),
('00003','10/12/2017','KH02','10')

INSERT INTO CTHD (SOHD,MALC,SOLUONG) VALUES
('00001','LC01','1'),
('00002','LC02','2'),
('00003','LC03','5')

------CAU 3------
ALTER TABLE LOAICAY ADD CONSTRAINT CK_GIA CHECK (GIA>250000 OR XUATXU <> 'Anh')

------CAU 4-----
/*
		THEM	XOA		SUA
HOADON	 -		 -		+(KHUYENMAI)
CTHD	 +       -      +(SOLUONG)
*/

CREATE TRIGGER R1
ON HOADON
FOR UPDATE
AS
BEGIN
	IF UPDATE (KHUYENMAI)
	BEGIN
		IF EXISTS (
			SELECT 1 FROM inserted h
			JOIN CTHD c ON c.SOHD = h.SOHD
			GROUP BY c.SOHD
			HAVING SUM(c.SOLUONG) >= 5 AND MIN(h.KHUYENMAI) < 10)
		BEGIN 
			RAISERROR ('Hoa don co so luong lon hon hoac bang 5 deu duoc giam gia 10 phan tram',16,1)
			ROLLBACK TRAN
		END
	END
END

CREATE TRIGGER R2
ON CTHD
FOR INSERT, update
AS 
BEGIN
     IF EXISTS (
		SELECT 1 FROM inserted c
		JOIN HOADON h ON h.SOHD = c.SOHD
		GROUP BY c.SOHD
		HAVING SUM(c.SOLUONG) >= 5 AND min(h.KHUYENMAI) < 10 )
     BEGIN
			RAISERROR ('Hoa don co so luong lon hon hoac bang 5 deu duoc giam gia 10 phan tram',16,2)
			ROLLBACK TRAN
	 END
END

-----CAU 5-----
SELECT SOHD, KHUYENMAI 
FROM HOADON
WHERE NGHD BETWEEN ('1/10/2017') AND ('31/12/2017')
ORDER BY KHUYENMAI ASC

-----CAU 6---------
SELECT lc.MALC, sum(SOLUONG) AS Tongsoluong
FROM LOAICAY lc
INNER JOIN CTHD c ON c.MALC = lc.MALC
INNER JOIN HOADON h ON c.SOHD = h.SOHD
WHERE month(NGHD) = 12 
GROUP BY lc.MALC
HAVING sum(c.SOLUONG) <=ALL(
						SELECT sum(SOLUONG) 
						FROM CTHD c
						INNER JOIN HOADON h ON h.SOHD = c.SOHD
						WHERE month(NGHD) = 12
						GROUP BY MALC
						)

-------CAU 7---------
(SELECT lc.MALC, lc.TENLC
FROM LOAICAY lc
INNER JOIN CTHD c ON c.MALC = lc.MALC
INNER JOIN HOADON h ON h.SOHD = c.SOHD
INNER JOIN KHACHHANG k ON k.MAKH = h.MAKH
WHERE LOAIKH = 'Thuong xuyen')
INTERSECT 
(SELECT lc.MALC, lc.TENLC
FROM LOAICAY lc
INNER JOIN CTHD c ON c.MALC = lc.MALC
INNER JOIN HOADON h ON h.SOHD = c.SOHD
INNER JOIN KHACHHANG k ON k.MAKH = h.MAKH
WHERE LOAIKH = 'Vang lai')

-----------CAU 8----------
SELECT MAKH,TENKH FROM KHACHHANG WHERE NOT EXISTS 
	(SELECT * FROM LOAICAY WHERE NOT EXISTS
		(SELECT * FROM HOADON 
		INNER JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
		WHERE HOADON.MAKH = KHACHHANG.MAKH AND CTHD.MALC = LOAICAY.MALC))

