CREATE DATABASE QUANLYBANHANG

-------- TAO BANG KHACH HANG ----------
CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) PRIMARY KEY, 
	HOTEN VARCHAR(40) NOT NULL,
	DCHI VARCHAR(50) NOT NULL,
	SODT VARCHAR(20) NOT NULL,
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY NOT NULL
);

--------------- TAO BANG NHAN VIEN --------------------
CREATE TABLE NHANVIEN
(
	MANV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40) NOT NULL,
	SODT VARCHAR(20) NOT NULL,
	NGVL SMALLDATETIME
);

--------------- TAO BANG SAN PHAM -------------------
CREATE TABLE SANPHAM
(
	MASP CHAR(4) PRIMARY KEY,
	TENSP VARCHAR(40) NOT NULL,
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY NOT NULL
);

-------------------- TAO BANG HOA DON -------------------------
CREATE TABLE HOADON
(
	SOHD INT PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(4) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	MANV CHAR(4) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	TRIGIA MONEY
);

------------------- TAO BANG CTHD ------------------------
CREATE TABLE CTHD
(
	SOHD INT FOREIGN KEY REFERENCES HOADON(SOHD),
	MASP CHAR(4) FOREIGN KEY REFERENCES SANPHAM(MASP),
	SL INT,
	PRIMARY KEY (SOHD, MASP)
);

ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20);

ALTER TABLE KHACHHANG ADD LOAIKH TINYINT;

ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100);

ALTER TABLE SANPHAM DROP COLUMN GHICHU;

ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH VARCHAR(20);

ALTER TABLE SANPHAM ADD CONSTRAINT CHK_DVT CHECK(DVT in ('cay', 'hop', 'cai', 'quyen', 'chuc'));
// ALTER TABLE SANPHAM ADD CONSTRAINT CHECK_DV CHECK ( DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));
ALTER TABLE SANPHAM ADD CONSTRAINT CHK_GIA CHECK(GIA >= 500);

ALTER TABLE CTHD ADD CONSTRAINT CHK_SL CHECK(SL >= 1);

ALTER TABLE KHACHHANG ADD CONSTRAINT CHK_NGDK CHECK(NGDK > NGSINH);

SELECT * FROM KHACHHANG
SELECT * FROM NHANVIEN
SELECT * FROM SANPHAM
SELECT * FROM HOADON
SELECT * FROM CTHD
